version: "3.7"
services:
    app-nginx:
        build:
            context: docker
            dockerfile: development/nginx/Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
        depends_on:
            - app-php-fpm

    app-php-fpm:
        build:
            context: docker
            dockerfile: development/php-fpm/Dockerfile
        environment:
            APP_ENV: dev
        volumes:
            - ./:/var/www

    app-php-cli:
        tty: true
        build:
            context: docker
            dockerfile: development/php-cli/Dockerfile
        environment:
            APP_ENV: dev
        volumes:
            - ./:/var/www

    app-nodejs:
        tty: true
        image: node:14-alpine
        volumes:
            - ./:/var/www
        working_dir: /var/www

    ###> symfony/mailer ###
    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]
    ###< symfony/mailer ###
