# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: en
    supported_locales: en|cn

    # application options
    app_name: '%env(APP_NAME)%'
    app_logo_tron: '%kernel.project_dir%/assets/tron.png'
    app_tron_node: '%env(APP_TRON_NODE)%'
    app_tron_balance: '%env(APP_TRON_BALANCE)%'
    app_email_from: '%env(APP_EMAIL_FROM)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            string $pathProject: '%kernel.project_dir%'
            string $pathCache: '%kernel.cache_dir%'
            string $urlTronNode: '%app_tron_node%'
            string $urlTronBalance: '%app_tron_balance%'
            string $emailFrom: '%app_email_from%'
            string $appName: '%app_name%'
            string $appEnv: '%env(APP_ENV)%'
            string $appPHP: '%env(APP_PHP)%'
            string $appTgToken: '%env(APP_TG_TOKEN)%'
            bool $appDebug: '%env(bool:APP_DEBUG)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Twig extension
    App\Helper\TwigExtension:
        arguments:
            $logo: '%app_logo_tron%'

    Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

    App\Handler\HandlerFactory:
        arguments:
            - "@service_container"

    App\Handler\:
        public: true
        resource: '../src/Handler/'
